services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: ai-hmis-frontend:latest
    container_name: ai-hmis-frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: ai-hmis-backend:latest
    container_name: ai-hmis-backend
    ports:
      - "8080:8080"
