services:
  frontend:
    build:
      context: ../../ai-hmis-frontend
      dockerfile: frontend/Dockerfile
  backend:
    build:
      context: ../../aihmisbackend
      dockerfile: backend/Dockerfile

# docker compose up --build