services:
  frontend:
    build:
      context: ../ai-hmis-frontend
      dockerfile: ../ai-hmis-devops/docker/frontend/Dockerfile
  backend:
    build:
      context: ../aihmisbackend
      dockerfile: ../ai-hmis-devops/docker/backend/Dockerfile

# docker compose up --build