apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ai-hmis-namespace
type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: ai_hmis
  MYSQL_USER: phani
  MYSQL_PASSWORD: password123