apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ai-hmis-namespace
  labels:
    app: mysql
    project: ai-hmis
spec:
  type: ClusterIP
  selector:
    app: mysql
    project: ai-hmis
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP