apiVersion: v1
kind: Service
metadata:
  name: ai-hmis-frontend-service
  namespace: ai-hmis-namespace
  labels:
    app: ai-hmis-frontend-nginx
    project: ai-hmis
spec:
  # type: LoadBalancer   as i used aws elastic load balancer controller installed in terraform 07-eks-addons i used ClusterIP
  type: ClusterIP 
  selector:
    app: ai-hmis-frontend-nginx
    project: ai-hmis
  ports:
  - port: 80
    targetPort: 80