name: Backend CI

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ai-hmis/backend

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Checkout DevOps Repository
      - name: Checkout DevOps Repo
        uses: actions/checkout@v4

      # Checkout Backend Repository
      - name: Checkout Backend Repo
        uses: actions/checkout@v4
        with:
          repository: phanis-git/aihmisbackend    # Change if your repo name is different
          path: backend
          token: ${{ secrets.GH_PAT }}

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        working-directory: backend
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      # Push Commit SHA Tag
      - name: Push Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      # Tag and Push Latest
      - name: Tag Latest
        run: |
          docker tag \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest